# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Checkout Infrastructure repo
      uses: actions/checkout@v2
      with:
        path: dec-blueprints
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run NPM CI
      run: |
          cd dec-blueprints
          npm ci
    - name: Run NPM Build
      run: |
          cd dec-blueprints
          npm run build --if-present
    - name: Run Linters
      run: |
          cd dec-blueprints
          npm run lint
    - name: Run Unit Tests
      run: |
          cd dec-blueprints
          npm test